# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/car_rental_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=carRentalSuperSecretKey1234567890ABCDEFGHIJKLMNOP
jwt.expiration=86400000

# DISABLE EMAIL COMPLETELY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# RAZORPAY
razorpay.key.id=rzp_test_Sd4UzYYzPnmSV2
razorpay.key.secret=VdHy5VrKlavb3dSjljQhSKSD

# APP
server.port=8080
spring.application.name=car-rental-system
spring.jackson.serialization.write-dates-as-timestamps=false